services:
  cuda-env:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        user: "${USER:-user}"  # ホストマシンのユーザー名を使用
        uid: "${UID:-1000}"    # ホストマシンのUID
        gid: "${GID:-1000}"    # ホストマシンのGID
    image: my-cuda-env:latest
    container_name: cuda-container
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - PATH=/opt/conda/bin:$PATH
    volumes:
      - .:/workspace  # ホストのカレントディレクトリをコンテナ内にマウント
    working_dir: /workspace  # 作業ディレクトリ
    stdin_open: true  # 標準入力を保持
    tty: true         # インタラクティブなTTYを使用可能
